//! EdgeFit 诊断策略：把模型事实与目标合同转换为稳定、可自动阻断的业务结论。

use edgefit_analyze::Metrics;
use edgefit_ir::{AttributeValue, NormalizedModel};
use edgefit_target::TargetProfile;
use std::collections::BTreeSet;

#[derive(Clone, Debug, PartialEq)]
pub struct Diagnostic {
    pub id: String,
    pub severity: String,
    pub category: String,
    pub location: Option<String>,
    pub title: String,
    pub message: String,
    pub actual: Option<String>,
    pub budget: Option<String>,
    pub suggestions: Vec<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct PolicyResult {
    pub status: String,
    pub diagnostics: Vec<Diagnostic>,
    pub suppressed_diagnostics: Vec<Diagnostic>,
}

fn status_for(diagnostics: &[Diagnostic]) -> String {
    if diagnostics.iter().any(|diag| diag.severity == "error") {
        "fail".to_string()
    } else {
        "pass".to_string()
    }
}

pub fn suppress_diagnostics(result: PolicyResult, suppressed_ids: &[String]) -> PolicyResult {
    let suppressed_ids: BTreeSet<&str> = suppressed_ids.iter().map(String::as_str).collect();
    if suppressed_ids.is_empty() {
        return result;
    }

    let mut diagnostics = Vec::new();
    let mut suppressed_diagnostics = result.suppressed_diagnostics;
    for diagnostic in result.diagnostics {
        if suppressed_ids.contains(diagnostic.id.as_str()) {
            suppressed_diagnostics.push(diagnostic);
        } else {
            diagnostics.push(diagnostic);
        }
    }

    PolicyResult {
        status: status_for(&diagnostics),
        diagnostics,
        suppressed_diagnostics,
    }
}

pub fn evaluate(
    model: &NormalizedModel,
    profile: &TargetProfile,
    metrics: &Metrics,
) -> PolicyResult {
    let mut diagnostics = Vec::new();

    if !model.adapter_generated {
        diagnostics.push(Diagnostic {
            id: "EF0001".to_string(),
            severity: "warning".to_string(),
            category: "provenance".to_string(),
            location: Some("model.normalization".to_string()),
            title: "Normalized model metadata is a trusted input".to_string(),
            message: "This .edgefit.json was not generated by the in-process ONNX adapter, so model file bytes, external-data count, and declared tensor bytes are trusted metadata.".to_string(),
            actual: Some("trusted_normalized_json".to_string()),
            budget: Some("adapter_generated_onnx".to_string()),
            suggestions: vec![
                "Run EdgeFit directly on the original .onnx artifact for an adapter-generated analysis"
                    .to_string(),
                "Treat pre-normalized JSON as reviewed input rather than untrusted CI evidence"
                    .to_string(),
            ],
        });
    }

    if let Some(budget) = profile.model_file_budget_bytes {
        if metrics.model_file_bytes > budget {
            diagnostics.push(Diagnostic {
                id: "EF0401".to_string(),
                severity: "error".to_string(),
                category: "memory".to_string(),
                location: Some("model.file".to_string()),
                title: "Model file exceeds flash budget".to_string(),
                message: format!(
                    "Model file is {} bytes; budget is {} bytes.",
                    metrics.model_file_bytes, budget
                ),
                actual: Some(metrics.model_file_bytes.to_string()),
                budget: Some(budget.to_string()),
                suggestions: vec![
                    "Reduce parameters".to_string(),
                    "Apply int8 quantization".to_string(),
                ],
            });
        }
    }

    if profile.external_memory_allowed == Some(false) && metrics.external_data_file_count > 0 {
        diagnostics.push(Diagnostic {
            id: "EF0402".to_string(),
            severity: "error".to_string(),
            category: "memory".to_string(),
            location: Some("model.external_data".to_string()),
            title: "External ONNX data files are outside the target contract".to_string(),
            message: format!(
                "Model package uses {} external ONNX data file(s), but runtime.external_memory_allowed is false.",
                metrics.external_data_file_count
            ),
            actual: Some(metrics.external_data_file_count.to_string()),
            budget: Some("0".to_string()),
            suggestions: vec![
                "Embed weights into one ONNX file or stage them in an approved target storage path"
                    .to_string(),
                "Enable external memory only after confirming the deployment runtime contract"
                    .to_string(),
            ],
        });
    }

    if let Some(budget) = profile.peak_activation_budget_bytes {
        if metrics.unresolved_tensor_size_count > 0 || metrics.activation_planning_overflowed {
            diagnostics.push(Diagnostic {
                id: "EF0502".to_string(),
                severity: "error".to_string(),
                category: "memory".to_string(),
                location: Some("model.activations".to_string()),
                title: "Activation memory budget cannot be proven".to_string(),
                message: format!(
                    "{} activation tensors have no concrete or profile-bounded size; planner_overflowed={}; the {}-byte budget cannot be verified safely.",
                    metrics.unresolved_tensor_size_count,
                    metrics.activation_planning_overflowed,
                    budget
                ),
                actual: Some("unresolved".to_string()),
                budget: Some(budget.to_string()),
                suggestions: vec![
                    "Add missing shape metadata or symbol bounds to the target profile".to_string(),
                    "Export concrete intermediate tensor shapes".to_string(),
                    "Reduce tensor size, alignment, or workspace if the arena exceeds representable bounds"
                        .to_string(),
                ],
            });
        }
        if metrics.planned_activation_arena_bytes > budget {
            diagnostics.push(Diagnostic {
                id: "EF0501".to_string(),
                severity: "error".to_string(),
                category: "memory".to_string(),
                location: Some("model.activations".to_string()),
                title: "Planned activation arena exceeds RAM budget".to_string(),
                message: format!(
                    "Planned activation arena is {} bytes at {}; budget is {} bytes.",
                    metrics.planned_activation_arena_bytes,
                    format_peak_location(metrics),
                    budget
                ),
                actual: Some(metrics.planned_activation_arena_bytes.to_string()),
                budget: Some(budget.to_string()),
                suggestions: vec![
                    "Lower input resolution".to_string(),
                    "Review tensor lifetimes, operator workspace, and verified in-place reuse"
                        .to_string(),
                ],
            });
        }
    }

    if profile.weights_residency.as_deref() == Some("ram") {
        let ram_budget = profile.ram_bytes.unwrap_or(0);
        let unresolved = metrics.unresolved_initializer_size_count
            + metrics.unresolved_tensor_size_count;
        if unresolved > 0 || metrics.activation_planning_overflowed {
            diagnostics.push(Diagnostic {
                id: "EF0503".to_string(),
                severity: "error".to_string(),
                category: "memory".to_string(),
                location: Some("model.ram_resident_weights".to_string()),
                title: "RAM-resident weight budget cannot be proven".to_string(),
                message: format!(
                    "Weights reside in RAM, but {} weight or activation tensor sizes remain unresolved and planner_overflowed={}.",
                    unresolved,
                    metrics.activation_planning_overflowed
                ),
                actual: Some("unresolved".to_string()),
                budget: Some(ram_budget.to_string()),
                suggestions: vec![
                    "Export concrete initializer and activation shapes".to_string(),
                    "Use profile symbol bounds for dynamic activation dimensions".to_string(),
                ],
            });
        } else {
            let total = metrics
                .initializer_bytes
                .saturating_add(metrics.planned_activation_arena_bytes);
            if total > ram_budget {
                diagnostics.push(Diagnostic {
                    id: "EF0503".to_string(),
                    severity: "error".to_string(),
                    category: "memory".to_string(),
                    location: Some("model.ram_resident_weights".to_string()),
                    title: "RAM-resident weights and activations exceed RAM budget".to_string(),
                    message: format!(
                        "RAM-resident weights plus the planned activation arena use {} bytes; RAM budget is {} bytes.",
                        total, ram_budget
                    ),
                    actual: Some(total.to_string()),
                    budget: Some(ram_budget.to_string()),
                    suggestions: vec![
                        "Move weights to flash or file storage when the runtime supports it"
                            .to_string(),
                        "Reduce model parameters or activation size".to_string(),
                    ],
                });
            }
        }
    }

    let disallowed_shape_count = if profile.static_shapes_required {
        metrics.dynamic_tensor_count
    } else if !profile.allow_unknown_dims {
        metrics.unresolved_tensor_size_count
    } else {
        0
    };
    if disallowed_shape_count > 0 {
        diagnostics.push(Diagnostic {
            id: "EF0101".to_string(),
            severity: "error".to_string(),
            category: "shape".to_string(),
            location: Some("graph.shapes".to_string()),
            title: "Target requires static tensor shapes".to_string(),
            message: format!(
                "{} tensors violate the target shape policy.",
                disallowed_shape_count
            ),
            actual: Some(disallowed_shape_count.to_string()),
            budget: Some("0".to_string()),
            suggestions: vec![
                "Run ONNX shape inference".to_string(),
                "Export with fixed input dimensions".to_string(),
            ],
        });
    }

    if profile.dynamic_allocation_allowed == Some(false)
        && !profile.static_shapes_required
        && metrics.dynamic_tensor_count > 0
    {
        diagnostics.push(Diagnostic {
            id: "EF0105".to_string(),
            severity: "error".to_string(),
            category: "shape".to_string(),
            location: Some("graph.shapes".to_string()),
            title: "Target disallows dynamic allocation".to_string(),
            message: format!(
                "{} tensors have symbolic or unknown dimensions, but runtime.dynamic_allocation_allowed is false.",
                metrics.dynamic_tensor_count
            ),
            actual: Some(metrics.dynamic_tensor_count.to_string()),
            budget: Some("0".to_string()),
            suggestions: vec![
                "Export fixed tensor shapes".to_string(),
                "Enable dynamic allocation only after confirming runtime memory behavior"
                    .to_string(),
            ],
        });
    }

    if metrics.shape_inference_status == "failed" {
        diagnostics.push(Diagnostic {
            id: "EF0103".to_string(),
            severity: if profile.static_shapes_required || !profile.allow_unknown_dims {
                "error"
            } else {
                "warning"
            }
            .to_string(),
            category: "shape".to_string(),
            location: Some("graph.shape_inference".to_string()),
            title: "ONNX shape inference failed".to_string(),
            message: metrics
                .shape_inference_error
                .as_deref()
                .map(|error| format!("ONNX shape inference failed; analysis used the checker-approved graph: {error}"))
                .unwrap_or_else(|| {
                    "ONNX shape inference failed; analysis used the checker-approved graph."
                        .to_string()
                }),
            actual: Some("failed".to_string()),
            budget: Some("pass".to_string()),
            suggestions: vec![
                "Resolve custom operator schemas or export shape metadata".to_string(),
                "Review EF0104 and EF0502 before accepting this model".to_string(),
            ],
        });
    }

    for item in &metrics.tensor_rank_violations {
        diagnostics.push(Diagnostic {
            id: "EF0102".to_string(),
            severity: "error".to_string(),
            category: "shape".to_string(),
            location: Some(format!("tensor:{}", item.tensor)),
            title: "Tensor rank exceeds target profile limit".to_string(),
            message: format!(
                "Tensor {} has rank {}; target maximum rank is {}.",
                item.tensor, item.rank, item.max_rank
            ),
            actual: Some(item.rank.to_string()),
            budget: Some(item.max_rank.to_string()),
            suggestions: vec![
                "Reduce tensor rank in the export path".to_string(),
                "Use a target profile with a higher rank limit".to_string(),
            ],
        });
    }

    if metrics.peak_activation_confidence != "high" {
        diagnostics.push(Diagnostic {
            id: "EF0104".to_string(),
            severity: if profile.static_shapes_required {
                "error"
            } else {
                "warning"
            }
            .to_string(),
            category: "shape".to_string(),
            location: Some("graph.shape_inference".to_string()),
            title: "Activation memory estimate has reduced confidence".to_string(),
            message: format!(
                "Peak activation confidence is {}; {} tensors use profile bounds and {} tensor sizes remain unresolved.",
                metrics.peak_activation_confidence,
                metrics.bounded_dynamic_tensor_count,
                metrics.unresolved_tensor_size_count
            ),
            actual: Some(metrics.peak_activation_confidence.clone()),
            budget: Some("high".to_string()),
            suggestions: vec![
                "Run ONNX shape inference before EdgeFit analysis".to_string(),
                "Export a model with concrete intermediate shapes".to_string(),
            ],
        });
    }

    for op in &metrics.unsupported_ops {
        diagnostics.push(Diagnostic {
            id: "EF0201".to_string(),
            severity: "error".to_string(),
            category: "operator".to_string(),
            location: Some(format!("op:{op}")),
            title: "Operator is outside the target profile".to_string(),
            message: format!("Operator {op} is absent from the target allowlist."),
            actual: Some(op.clone()),
            budget: None,
            suggestions: vec![
                "Change the model graph".to_string(),
                "Use a broader target profile".to_string(),
            ],
        });
    }

    let used_domains = model
        .nodes
        .iter()
        .map(|node| node.domain.clone())
        .collect::<BTreeSet<_>>();
    for domain in used_domains {
        let Some(version) = metrics.opset_versions.get(&domain) else {
            if model.adapter_generated {
                diagnostics.push(Diagnostic {
                    id: "EF0204".to_string(),
                    severity: "error".to_string(),
                    category: "operator".to_string(),
                    location: Some(format!("domain:{domain}")),
                    title: "Operator domain has no ONNX opset import".to_string(),
                    message: format!(
                        "Model uses domain {domain}, but normalization recorded no opset import for it."
                    ),
                    actual: None,
                    budget: None,
                    suggestions: vec![
                        "Export a valid ONNX model with an explicit domain opset import"
                            .to_string(),
                    ],
                });
            }
            continue;
        };
        if let Some(maximum) = profile.max_opset_versions.get(&domain) {
            if version > maximum {
                diagnostics.push(Diagnostic {
                    id: "EF0204".to_string(),
                    severity: "error".to_string(),
                    category: "operator".to_string(),
                    location: Some(format!("domain:{domain}")),
                    title: "ONNX opset exceeds the target profile limit".to_string(),
                    message: format!(
                        "Domain {domain} uses opset {version}; target maximum is {maximum}."
                    ),
                    actual: Some(version.to_string()),
                    budget: Some(maximum.to_string()),
                    suggestions: vec![
                        "Export the model with a supported opset".to_string(),
                        "Raise the target limit only after runtime compatibility verification"
                            .to_string(),
                    ],
                });
            }
        } else if model.adapter_generated {
            diagnostics.push(Diagnostic {
                id: "EF0205".to_string(),
                // 原始 ONNX 已确认实际使用该 domain；profile 缺少上限时无法证明运行时兼容性，必须关闭放行。
                severity: "error".to_string(),
                category: "operator".to_string(),
                location: Some(format!("domain:{domain}")),
                title: "Target profile has no ONNX opset limit".to_string(),
                message: format!(
                    "Domain {domain} uses opset {version}, but the target profile does not declare an opsets.{domain} maximum."
                ),
                actual: Some(version.to_string()),
                budget: None,
                suggestions: vec![
                    "Add the maximum runtime-supported opset for this domain to the target profile"
                        .to_string(),
                ],
            });
        }
    }

    for item in &metrics.op_dtype_violations {
        diagnostics.push(Diagnostic {
            id: "EF0202".to_string(),
            severity: "error".to_string(),
            category: "operator".to_string(),
            location: Some(format!("op:{} tensor:{}", item.op_type, item.tensor)),
            title: "Operator tensor dtype is outside the op rule".to_string(),
            message: format!(
                "Operator {} sees tensor {} with dtype {}; allowed dtypes are [{}].",
                item.op_type,
                item.tensor,
                item.dtype,
                item.allowed.join(", ")
            ),
            actual: Some(item.dtype.clone()),
            budget: Some(item.allowed.join(",")),
            suggestions: vec![
                "Quantize or cast the tensor before this operator".to_string(),
                "Adjust the target profile only if the runtime supports this dtype".to_string(),
            ],
        });
    }

    for item in &metrics.op_rank_violations {
        diagnostics.push(Diagnostic {
            id: "EF0203".to_string(),
            severity: "error".to_string(),
            category: "operator".to_string(),
            location: Some(format!("op:{} tensor:{}", item.op_type, item.tensor)),
            title: "Operator tensor rank exceeds the op rule".to_string(),
            message: format!(
                "Operator {} sees tensor {} with rank {}; op maximum rank is {}.",
                item.op_type, item.tensor, item.rank, item.max_rank
            ),
            actual: Some(item.rank.to_string()),
            budget: Some(item.max_rank.to_string()),
            suggestions: vec![
                "Change the export shape".to_string(),
                "Use an operator rule that matches the target runtime".to_string(),
            ],
        });
    }

    append_operator_contract_diagnostics(model, profile, &mut diagnostics);

    for dtype in &metrics.unsupported_dtypes {
        diagnostics.push(Diagnostic {
            id: "EF0301".to_string(),
            severity: "error".to_string(),
            category: "dtype".to_string(),
            location: Some(format!("dtype:{dtype}")),
            title: "Tensor dtype is outside the target profile".to_string(),
            message: format!("Tensor dtype {dtype} is absent from dtype.allowed."),
            actual: Some(dtype.clone()),
            budget: None,
            suggestions: vec!["Export or quantize the model to an allowed dtype".to_string()],
        });
    }

    for tensor in &metrics.unknown_dtype_tensors {
        diagnostics.push(Diagnostic {
            id: "EF0302".to_string(),
            severity: "error".to_string(),
            category: "dtype".to_string(),
            location: Some(format!("tensor:{tensor}")),
            title: "Tensor dtype is unknown".to_string(),
            message: format!(
                "Tensor {tensor} has no dtype metadata, so target compatibility cannot be proven."
            ),
            actual: Some("unknown".to_string()),
            budget: Some("known target-supported dtype".to_string()),
            suggestions: vec![
                "Export complete value_info dtype metadata".to_string(),
                "Run ONNX shape/type inference with the required operator schemas".to_string(),
            ],
        });
    }

    if profile.quantization_required {
        if let Some(minimum) = profile.min_quantized_weight_fraction {
            if metrics.quantized_initializer_fraction < minimum {
                diagnostics.push(Diagnostic {
                    id: "EF0601".to_string(),
                    severity: "error".to_string(),
                    category: "quantization".to_string(),
                    location: Some("initializers.quantization".to_string()),
                    title: "Quantized initializer fraction is below target requirement".to_string(),
                    message: format!(
                        "Quantized initializer fraction is {:.3}; required minimum is {:.3}.",
                        metrics.quantized_initializer_fraction, minimum
                    ),
                    actual: Some(format!("{:.6}", metrics.quantized_initializer_fraction)),
                    budget: Some(format!("{minimum:.6}")),
                    suggestions: vec![
                        "Quantize remaining weights".to_string(),
                        "Use a target profile that allows float weights".to_string(),
                    ],
                });
            }
        }

        // QDQ/QOperator 只是静态格式证据，缺失时告警而不直接替代 runtime 判定。
        let non_int8_state_remains = metrics.quantized_initializer_fraction < 1.0
            || !metrics.non_int8_graph_io.is_empty()
            || !metrics.ops_without_int8_path.is_empty();
        let minimum_operator_coverage = profile.min_quantized_operator_coverage.unwrap_or(0.0);
        let coverage_below_requirement =
            metrics.quantization_operator_coverage < minimum_operator_coverage;
        let missing_representation_evidence =
            metrics.quantization_covered_node_count == 0 && non_int8_state_remains;
        if non_int8_state_remains
            && (coverage_below_requirement || missing_representation_evidence)
        {
            diagnostics.push(Diagnostic {
                id: "EF0602".to_string(),
                severity: "warning".to_string(),
                category: "quantization".to_string(),
                location: Some("graph.quantization".to_string()),
                title: "Quantized operator coverage is below the target requirement".to_string(),
                message: format!(
                    "QDQ/QOperator representation is {}; target-eligible operator coverage is {:.3}, below the required {:.3}.",
                    metrics.quantization_representation,
                    metrics.quantization_operator_coverage,
                    minimum_operator_coverage
                ),
                actual: Some(format!("{:.6}", metrics.quantization_operator_coverage)),
                budget: Some(format!("{minimum_operator_coverage:.6}")),
                suggestions: vec![
                    "Export the ONNX model with QDQ or QOperator quantization".to_string(),
                    "Verify the target runtime's supported quantization format before conversion"
                        .to_string(),
                ],
            });
        }

        // dtype 分布用于解释 EF0601；合法的浮点 scale 常量不应单独造成失败。
        let floating_initializers = metrics
            .initializer_dtype_distribution
            .iter()
            .filter(|item| is_float_dtype(&item.dtype))
            .collect::<Vec<_>>();
        let floating_initializer_bytes = floating_initializers
            .iter()
            .map(|item| item.bytes)
            .sum::<u64>();
        let floating_initializer_count = floating_initializers
            .iter()
            .map(|item| item.tensor_count)
            .sum::<u64>();
        let initializer_distribution_needs_review = profile
            .min_quantized_weight_fraction
            .map(|minimum| metrics.quantized_initializer_fraction < minimum)
            .unwrap_or(profile.require_int8);
        if floating_initializer_bytes > 0 && initializer_distribution_needs_review {
            diagnostics.push(Diagnostic {
                id: "EF0603".to_string(),
                severity: "warning".to_string(),
                category: "quantization".to_string(),
                location: Some("initializers.dtype_distribution".to_string()),
                title: "Floating-point initializers remain".to_string(),
                message: format!(
                    "Initializer dtype distribution contains {} floating-point bytes across {} tensors: {}.",
                    floating_initializer_bytes,
                    floating_initializer_count,
                    format_initializer_dtype_distribution(metrics)
                ),
                actual: Some(format_initializer_dtype_distribution(metrics)),
                budget: None,
                suggestions: vec![
                    "Review the listed initializer dtypes and quantize remaining weight tensors"
                        .to_string(),
                    "Keep floating-point scale constants when required by the selected ONNX quantization format"
                        .to_string(),
                ],
            });
        }

        // 显式 int8 约束只检查图边界和 profile 声明的 kernel 路径。
        if profile.require_int8 {
            for item in &metrics.non_int8_graph_io {
                diagnostics.push(Diagnostic {
                    id: "EF0604".to_string(),
                    severity: "error".to_string(),
                    category: "quantization".to_string(),
                    location: Some(format!("tensor:{}", item.tensor)),
                    title: "Graph I/O dtype violates the target int8 requirement".to_string(),
                    message: format!(
                        "Graph {} tensor {} has dtype {}; target requires int8 or uint8.",
                        item.boundary, item.tensor, item.dtype
                    ),
                    actual: Some(item.dtype.clone()),
                    budget: Some("int8,uint8".to_string()),
                    suggestions: vec![
                        "Export graph inputs and outputs with the required integer dtype"
                            .to_string(),
                        "Disable quantization.require_int8 only when the runtime performs boundary quantization"
                            .to_string(),
                    ],
                });
            }

            for op in &metrics.ops_without_int8_path {
                diagnostics.push(Diagnostic {
                    id: "EF0605".to_string(),
                    severity: "error".to_string(),
                    category: "quantization".to_string(),
                    location: Some(format!("op:{op}")),
                    title: "Operator has no int8 path in the target profile".to_string(),
                    message: format!(
                        "Operator {op} is used by the model, but its target rule exposes no int8 or uint8 dtype path."
                    ),
                    actual: Some(op.clone()),
                    budget: Some("int8 or uint8 kernel path".to_string()),
                    suggestions: vec![
                        "Replace or fuse this operator with a quantization-compatible graph pattern"
                            .to_string(),
                        "Add an integer dtype to the target rule only after verifying runtime kernel support"
                            .to_string(),
                    ],
                });
            }
        }
    }

    PolicyResult {
        status: status_for(&diagnostics),
        diagnostics,
        suppressed_diagnostics: Vec::new(),
    }
}

/// 将节点属性和逐端口 dtype 与 target 合同逐项对照；缺失或未知事实一律关闭放行。
fn append_operator_contract_diagnostics(
    model: &NormalizedModel,
    profile: &TargetProfile,
    diagnostics: &mut Vec<Diagnostic>,
) {
    for (node_index, node) in model.nodes.iter().enumerate() {
        let Some(rule) = profile.op_rule(&node.domain, &node.op_type) else {
            continue;
        };
        for (attribute, allowed) in &rule.attributes {
            let actual_value = node.attributes.get(attribute);
            if actual_value.is_some_and(|value| allowed.contains(value)) {
                continue;
            }
            let actual = actual_value.map(canonical_attribute_value);
            diagnostics.push(Diagnostic {
                id: "EF0206".to_string(),
                severity: "error".to_string(),
                category: "operator".to_string(),
                location: Some(format!("node:{node_index} attribute:{attribute}")),
                title: "Operator attribute is outside the target contract".to_string(),
                message: format!(
                    "Operator {} attribute {} is {}; allowed values are [{}].",
                    node.op_type,
                    attribute,
                    actual.as_deref().unwrap_or("missing"),
                    allowed
                        .iter()
                        .map(canonical_attribute_value)
                        .collect::<Vec<_>>()
                        .join(", ")
                ),
                actual,
                budget: Some(
                    allowed
                        .iter()
                        .map(canonical_attribute_value)
                        .collect::<Vec<_>>()
                        .join(","),
                ),
                suggestions: vec![
                    "Export the operator with an attribute value supported by the target runtime"
                        .to_string(),
                    "Expand the target contract only after verifying the runtime kernel"
                        .to_string(),
                ],
            });
        }
        append_port_contracts(
            node_index,
            "input",
            &node.op_type,
            &node.inputs,
            &rule.input_dtypes,
            model,
            diagnostics,
        );
        append_port_contracts(
            node_index,
            "output",
            &node.op_type,
            &node.outputs,
            &rule.output_dtypes,
            model,
            diagnostics,
        );
    }
}

fn append_port_contracts(
    node_index: usize,
    direction: &str,
    op_type: &str,
    tensors: &[String],
    contracts: &std::collections::BTreeMap<usize, BTreeSet<String>>,
    model: &NormalizedModel,
    diagnostics: &mut Vec<Diagnostic>,
) {
    for (port, allowed) in contracts {
        let tensor_name = tensors.get(*port).filter(|name| !name.is_empty());
        let actual = tensor_name
            .and_then(|name| model.tensors.get(name))
            .and_then(|tensor| tensor.dtype.as_deref())
            .map(edgefit_ir::normalize_dtype);
        if actual.as_ref().is_some_and(|dtype| allowed.contains(dtype)) {
            continue;
        }
        diagnostics.push(Diagnostic {
            id: "EF0207".to_string(),
            severity: "error".to_string(),
            category: "operator".to_string(),
            location: Some(format!("node:{node_index} {direction}:{port}")),
            title: "Operator port dtype is outside the target contract".to_string(),
            message: format!(
                "Operator {op_type} {direction} port {port} has dtype {}; allowed dtypes are [{}].",
                actual.as_deref().unwrap_or("missing"),
                allowed.iter().cloned().collect::<Vec<_>>().join(", ")
            ),
            actual,
            budget: Some(allowed.iter().cloned().collect::<Vec<_>>().join(",")),
            suggestions: vec![
                "Export or cast the tensor to the dtype required at this operator port"
                    .to_string(),
            ],
        });
    }
}

fn canonical_attribute_value(value: &AttributeValue) -> String {
    match value {
        AttributeValue::Int(value) => format!("int:{value}"),
        AttributeValue::Float(value) => format!("float:{:e}", value.as_f64()),
        AttributeValue::String(value) => format!("string:{value}"),
        AttributeValue::Ints(values) => format!(
            "ints:{}",
            values.iter().map(ToString::to_string).collect::<Vec<_>>().join(";")
        ),
        AttributeValue::Floats(values) => format!(
            "floats:{}",
            values
                .iter()
                .map(|value| format!("{:e}", value.as_f64()))
                .collect::<Vec<_>>()
                .join(";")
        ),
        AttributeValue::Strings(values) => format!("strings:{}", values.join(";")),
        AttributeValue::Unknown { onnx_type, reason } => {
            format!("unknown:{onnx_type}:{reason}")
        }
    }
}

fn is_float_dtype(dtype: &str) -> bool {
    matches!(dtype, "float16" | "float32" | "float64" | "bfloat16")
}

fn format_initializer_dtype_distribution(metrics: &Metrics) -> String {
    metrics
        .initializer_dtype_distribution
        .iter()
        .map(|item| format!("{}:{} tensors/{} bytes", item.dtype, item.tensor_count, item.bytes))
        .collect::<Vec<_>>()
        .join(", ")
}

/// 将峰值事件压缩成可直接定位的业务提示，避免用户再翻完整 allocation trace。
fn format_peak_location(metrics: &Metrics) -> String {
    if metrics.peak_activation_event != "node" {
        return metrics.peak_activation_event.clone();
    }
    let mut parts = vec!["node".to_string()];
    if let Some(index) = metrics.peak_activation_node_index {
        parts.push(format!("#{index}"));
    }
    if let Some(name) = metrics.peak_activation_node_name.as_deref() {
        parts.push(name.to_string());
    }
    if let Some(op_type) = metrics.peak_activation_op_type.as_deref() {
        parts.push(format!("({op_type})"));
    }
    parts.join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use edgefit_analyze::{analyze, Metrics};
    use edgefit_ir::{AttributeValue, NodeInfo, NormalizedModel, TensorInfo};
    use edgefit_target::{parse_profile, OpRule, ProfileMetadata, TargetProfile};
    use std::collections::{BTreeMap, BTreeSet};
    use std::path::PathBuf;

    #[test]
    fn emits_memory_diagnostic() {
        let metrics = Metrics {
            model_file_bytes: 20,
            external_data_file_count: 0,
            opset_versions: BTreeMap::new(),
            initializer_bytes: 0,
            unresolved_initializer_size_count: 0,
            estimated_peak_activation_bytes: 0,
            planned_activation_arena_bytes: 0,
            activation_tensor_alignment_bytes: 1,
            activation_planner_algorithm: "linear_scan_best_fit_v2".to_string(),
            activation_planning_overflowed: false,
            peak_activation_event: "graph_start".to_string(),
            peak_activation_node_index: None,
            peak_activation_node_name: None,
            peak_activation_op_type: None,
            peak_activation_live_allocated_bytes: 0,
            peak_activation_workspace_bytes: 0,
            peak_activation_fragmentation_bytes: 0,
            inplace_reuse_count: 0,
            inplace_avoided_allocation_bytes: 0,
            peak_activation_contributors: vec![],
            activation_allocation_trace: vec![],
            peak_activation_confidence: "high".to_string(),
            shape_inference_status: "not_recorded".to_string(),
            shape_inference_error: None,
            dynamic_tensor_count: 0,
            bounded_dynamic_tensor_count: 0,
            unresolved_tensor_size_count: 0,
            unsupported_ops: vec![],
            unsupported_dtypes: vec![],
            unknown_dtype_tensors: vec![],
            tensor_rank_violations: vec![],
            op_dtype_violations: vec![],
            op_rank_violations: vec![],
            quantized_initializer_fraction: 1.0,
            initializer_dtype_distribution: vec![],
            quantization_representation: "none".to_string(),
            qdq_covered_node_count: 0,
            qoperator_node_count: 0,
            quantization_eligible_node_count: 0,
            quantization_covered_node_count: 0,
            quantization_operator_coverage: 0.0,
            target_requires_int8: false,
            int8_tensor_count: 0,
            uint8_tensor_count: 0,
            non_int8_graph_io: vec![],
            ops_without_int8_path: vec![],
            node_count: 0,
            tensor_count: 0,
        };
        let model = NormalizedModel {
            path: "m".to_string(),
            sha256: "s".to_string(),
            file_bytes: 20,
            external_data_file_count: 0,
            adapter_generated: true,
            opset_versions: BTreeMap::new(),
            shape_inference_status: "not_recorded".to_string(),
            shape_inference_error: None,
            inputs: vec![],
            outputs: vec![],
            tensors: BTreeMap::new(),
            nodes: vec![],
        };
        let profile = TargetProfile {
            source: PathBuf::new(),
            fingerprint: "test".to_string(),
            metadata: ProfileMetadata::unknown(),
            target_id: "t".to_string(),
            target_name: None,
            target_class: None,
            flash_bytes: None,
            ram_bytes: None,
            model_file_budget_bytes: Some(10),
            peak_activation_budget_bytes: None,
            weights_residency: None,
            tensor_alignment_bytes: 1,
            shape_max_rank: None,
            allow_unknown_dims: true,
            symbol_bounds: BTreeMap::new(),
            runtime_name: None,
            static_shapes_required: true,
            dynamic_allocation_allowed: None,
            external_memory_allowed: None,
            dtype_allowed: BTreeSet::from(["int8".to_string()]),
            dtype_preferred: None,
            fp32_allowed: None,
            max_opset_versions: BTreeMap::new(),
            allowed_ops: BTreeMap::new(),
            accelerator: None,
            replacement_recipes: BTreeMap::new(),
            quantization_required: false,
            require_int8: false,
            min_quantized_weight_fraction: None,
            min_quantized_operator_coverage: None,
        };
        let result = evaluate(&model, &profile, &metrics);
        assert_eq!(result.status, "fail");
        assert_eq!(result.diagnostics[0].id, "EF0401");
        let suppressed = suppress_diagnostics(result, &["EF0401".to_string()]);
        assert_eq!(suppressed.status, "pass");
        assert!(suppressed.diagnostics.is_empty());
        assert_eq!(suppressed.suppressed_diagnostics[0].id, "EF0401");

        let mut arena_metrics = metrics.clone();
        arena_metrics.estimated_peak_activation_bytes = 4;
        arena_metrics.planned_activation_arena_bytes = 12;
        let mut arena_profile = profile.clone();
        arena_profile.model_file_budget_bytes = None;
        arena_profile.peak_activation_budget_bytes = Some(10);
        let arena_result = evaluate(&model, &arena_profile, &arena_metrics);

        assert_eq!(arena_result.status, "fail");
        assert_eq!(arena_result.diagnostics[0].id, "EF0501");
        assert_eq!(arena_result.diagnostics[0].actual.as_deref(), Some("12"));

        let mut unresolved_metrics = metrics.clone();
        unresolved_metrics.unresolved_tensor_size_count = 1;
        let unresolved_result = evaluate(&model, &arena_profile, &unresolved_metrics);

        assert_eq!(unresolved_result.status, "fail");
        assert_eq!(unresolved_result.diagnostics[0].id, "EF0502");

        let mut overflow_metrics = metrics.clone();
        overflow_metrics.activation_planning_overflowed = true;
        let overflow_result = evaluate(&model, &arena_profile, &overflow_metrics);

        assert_eq!(overflow_result.status, "fail");
        assert_eq!(overflow_result.diagnostics[0].id, "EF0502");
    }

    #[test]
    fn missing_opset_limit_for_adapter_generated_model_fails_closed() {
        let model = NormalizedModel {
            path: "model.onnx".to_string(),
            sha256: "sha256".to_string(),
            file_bytes: 1,
            external_data_file_count: 0,
            adapter_generated: true,
            opset_versions: BTreeMap::from([("ai.onnx".to_string(), 18)]),
            shape_inference_status: "not_recorded".to_string(),
            shape_inference_error: None,
            inputs: vec![],
            outputs: vec![],
            tensors: BTreeMap::new(),
            nodes: vec![NodeInfo {
                name: Some("relu".to_string()),
                domain: "ai.onnx".to_string(),
                op_type: "Relu".to_string(),
                inputs: vec![],
                outputs: vec![],
                attributes: BTreeMap::new(),
            }],
        };
        let profile = TargetProfile {
            source: PathBuf::new(),
            fingerprint: "test".to_string(),
            metadata: ProfileMetadata::unknown(),
            target_id: "t".to_string(),
            target_name: None,
            target_class: None,
            flash_bytes: None,
            ram_bytes: None,
            model_file_budget_bytes: None,
            peak_activation_budget_bytes: None,
            weights_residency: None,
            tensor_alignment_bytes: 1,
            shape_max_rank: None,
            allow_unknown_dims: true,
            symbol_bounds: BTreeMap::new(),
            runtime_name: None,
            static_shapes_required: false,
            dynamic_allocation_allowed: None,
            external_memory_allowed: None,
            dtype_allowed: BTreeSet::new(),
            dtype_preferred: None,
            fp32_allowed: None,
            max_opset_versions: BTreeMap::new(),
            allowed_ops: BTreeMap::from([(
                ("ai.onnx".to_string(), "Relu".to_string()),
                OpRule {
                    dtypes: BTreeSet::new(),
                    input_dtypes: BTreeMap::new(),
                    output_dtypes: BTreeMap::new(),
                    attributes: BTreeMap::new(),
                    max_rank: None,
                    workspace_bytes: 0,
                    first_output_inplace_input_index: None,
                    cpu_cost: None,
                    npu_cost: None,
                },
            )]),
            accelerator: None,
            replacement_recipes: BTreeMap::new(),
            quantization_required: false,
            require_int8: false,
            min_quantized_weight_fraction: None,
            min_quantized_operator_coverage: None,
        };

        let metrics = analyze(&model, &profile);
        let result = evaluate(&model, &profile, &metrics);

        assert_eq!(result.status, "fail");
        assert_eq!(result.diagnostics.len(), 1);
        assert_eq!(result.diagnostics[0].id, "EF0205");
        assert_eq!(result.diagnostics[0].severity, "error");
    }

    #[test]
    fn fails_closed_for_attribute_and_port_contract_mismatches() {
        let model = NormalizedModel {
            path: "model.onnx".to_string(),
            sha256: "sha256".to_string(),
            file_bytes: 1,
            external_data_file_count: 0,
            adapter_generated: true,
            opset_versions: BTreeMap::from([("ai.onnx".to_string(), 13)]),
            shape_inference_status: "pass".to_string(),
            shape_inference_error: None,
            inputs: vec!["x".to_string()],
            outputs: vec!["y".to_string()],
            tensors: BTreeMap::from([
                (
                    "x".to_string(),
                    TensorInfo {
                        name: "x".to_string(),
                        dtype: Some("int8".to_string()),
                        shape: Some(vec![]),
                        bytes: None,
                        initializer: false,
                    },
                ),
                (
                    "y".to_string(),
                    TensorInfo {
                        name: "y".to_string(),
                        dtype: Some("float32".to_string()),
                        shape: Some(vec![]),
                        bytes: None,
                        initializer: false,
                    },
                ),
            ]),
            nodes: vec![NodeInfo {
                name: Some("softmax".to_string()),
                domain: "ai.onnx".to_string(),
                op_type: "Softmax".to_string(),
                inputs: vec!["x".to_string()],
                outputs: vec!["y".to_string()],
                attributes: BTreeMap::from([
                    ("axis".to_string(), AttributeValue::Int(2)),
                    (
                        "future".to_string(),
                        AttributeValue::Unknown {
                            onnx_type: 99,
                            reason: "unsupported".to_string(),
                        },
                    ),
                ]),
            }],
        };
        let profile = parse_profile(
            r#"
profile_version: edgefit.target.v1
metadata:
  source: test
  confidence: seed
  last_verified: 2026-07-11
target:
  id: test
  name: Test
  class: edge-cpu
memory:
  flash_bytes: 100
  ram_bytes: 100
  model_file_budget_bytes: 100
  peak_activation_budget_bytes: 100
  weights_residency: file
runtime:
  name: test
  static_shapes_required: false
  dynamic_allocation_allowed: true
  external_memory_allowed: true
dtype:
  allowed: [int8, float32]
  preferred: int8
  fp32_allowed: true
opsets:
  ai.onnx: 13
ops:
  allow:
    ai.onnx:
      Softmax:
        dtypes: [int8, float32]
        input_dtypes:
          0: [uint8]
        output_dtypes:
          0: [int8]
        attributes:
          axis: [int:1]
shape:
  max_rank: 4
  allow_unknown_dims: true
quantization:
  required: false
  require_int8: false
  min_quantized_weight_fraction: 0
  min_operator_coverage: 0
"#,
            PathBuf::from("target.yaml"),
        )
        .unwrap();

        let metrics = analyze(&model, &profile);
        let result = evaluate(&model, &profile, &metrics);

        assert_eq!(result.status, "fail");
        assert_eq!(result.diagnostics.iter().filter(|item| item.id == "EF0206").count(), 1);
        assert_eq!(result.diagnostics.iter().filter(|item| item.id == "EF0207").count(), 2);
        assert!(!result.diagnostics.iter().any(|item| item.id == "EF0202"));
    }
}
